#ifndef UNIDAD_MESSAGES_H
#define UNIDAD_MESSAGES_H

#include <glib.h>

typedef struct {
  const int code;
  const gchar *type;
  const gchar *message;
  const gchar *help;
} RuntimeMessage;

/* CONTENT is automatically generated by build_lib.py */
static const RuntimeMessage UNIDAD_MESSAGES[] = {
    /* <CONTENT> */
    {901, "IndexError", "list index out of range", NULL},
    {902, "IndexError", "string index out of range", NULL},
    {903, "IndexError", "list assignment index out of range", NULL},
    {904, "IndexError", "string assignment index out of range", NULL}
    /* </CONTENT> */
};

#endif
