#ifndef UNIDAD_MESSAGES_H
#define UNIDAD_MESSAGES_H

#include <glib.h>

typedef struct {
  const gchar *code;
  const gchar *type;
  const gchar *message;
  const gchar *help;
} RuntimeMessage;

/* CONTENT is automatically generated by build_lib.py */
static const RuntimeMessage runtime_messages[] = {
    /* <CONTENT> */

    /* </CONTENT> */
};

#endif
