#include "source.h"

/* This file is automatically generated by compiler.py */
const UnidadProgram UNIDAD_PROGRAM = {
    "tests/test.und",
    6,
    { "s = \"hello\"", "while s do {", "    echo(s)", "    s = s[1:]", "}", "" }
};