#include "source.h"

/* CONTENT is automatically generated by build_lib.py */
const UnidadProgram UNIDAD_PROGRAM = {
/* <CONTENT> */
"tests/test.und",
6,
{ "s = \"hello\"", "while s do {", "    echo(s)", "    s = s[1:]", "}", "" }
/* </CONTENT> */
};
