#ifndef NUMEROBIS_MESSAGES_H
#define NUMEROBIS_MESSAGES_H

#include <stdio.h>

typedef struct {
  const int code;
  const char *type;
  const char *message;
  const char *help;
} RuntimeMessage;

/* CONTENT is automatically generated by build_lib.py */
static const RuntimeMessage NUMEROBIS_MESSAGES[] = {
    /* <CONTENT> */
    {301, "ValueError", "failed to convert value to integer", NULL},
    {302, "ValueError", "failed to convert value to float", NULL},
    {303, "RuntimeError", "...", NULL},
    {304, "AssertionError", "...", NULL},
    {901, "IndexError", "list index out of range", NULL},
    {902, "IndexError", "string index out of range", NULL},
    {903, "IndexError", "list assignment index out of range", NULL},
    {904, "IndexError", "string assignment index out of range", NULL}
    /* </CONTENT> */
};

#endif
